config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include HTTParty
  base_uri 'http://127.0.0.1:3000'
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    response = self.class.get('/groups')
    @groups = JSON.parse(response.body)
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :content, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "タイトル", class: "block text-xs font-medium text-gray-700" %>
    <%= form.text_field :title, class: "mt-1 w-full rounded-md border-gray-200 shadow-sm sm:text-sm" %>
  </div>

  <div>
    <%= form.label "内容", class: "block text-xs font-medium text-gray-700" %>
    <%= form.text_field :content, class: "mt-1 w-full rounded-md border-gray-200 shadow-sm sm:text-sm" %>
  </div>

  <div>
    <%= form.label "完了", class: "block text-xs font-medium text-gray-700" %>
    <%= form.check_box :completed, class: "h-4 w-4 rounded border-gray-300 text-primary-600 shadow-sm focus:border-primary-300 focus:ring focus:ring-primary-200 focus:ring-opacity-50 focus:ring-offset-0 disabled:cursor-not-allowed disabled:text-gray-400" %>
  </div>

  <div>
    <%= form.submit value: "更新", class: "inline-block rounded-lg bg-blue-500 px-5 py-3 text-sm font-medium text-white" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" class="flow-root rounded-lg border border-gray-100 py-3 shadow-sm">
  <dl class="-my-3 divide-y divide-gray-100 text-sm">
    <div class="grid grid-cols-1 gap-1 p-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">タイトル</dt>
      <dd class="text-gray-700 sm:col-span-2"><%= todo.title %></dd>
    </div>

    <div class="grid grid-cols-1 gap-1 p-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">内容</dt>
      <dd class="text-gray-700 sm:col-span-2"><%= todo.content %></dd>
    </div>

    <div class="grid grid-cols-1 gap-1 p-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">ステータス</dt>
      <dd class="text-gray-700 sm:col-span-2">
        <%= todo.completed ? "完了" : "未完了" %>
      </dd>
    </div>
  </dl>
</div>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <span class="inline-flex -space-x-px overflow-hidden rounded-md border bg-white shadow-sm">
    <button class="inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative">
      <%= link_to "詳細に戻る", @todo %>
    </button>
    <button class="inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative">
      <%= link_to "一覧に戻る", todos_path %>
    </button>
  </span>
</div>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-3xl font-bold underline">Todos</h1>

<div class="w-1/2 overflow-x-auto">
  <table class="divide-y-4 divide-gray-200 bg-white text-sm">
    <thead class="ltr:text-left rtl:text-right">
      <tr>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">タイトル</th>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">ステータス</th>
      </tr>
    </thead>

    <tbody class="divide-y divide-gray-200">
      <% @todos.each do |todo| %>
        <tr class="hover:bg-gray-100 cursor-pointer" onclick="window.location='<%= todo_path(todo) %>';">
          <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 group-hover:text-gray-700"><%= todo.title %></td>
          <td class="flex justify-center px-4 py-2 text-gray-700"><%= todo.completed ? '完了' : '未完了' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<span class="inline-flex -space-x-px overflow-hidden rounded-md border bg-white shadow-sm">
  <button class="inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative">
    <%= link_to "新規", new_todo_path %>
  </button>
</span>

<ul>
  <% @groups.each do |group| %>
    <li><%= group['name'] %></li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1>New todo</h1>

<div class="w-1/2">
  <%= render "form", todo: @todo %>
</div>

<div>
  <span class="inline-flex -space-x-px overflow-hidden rounded-md border bg-white shadow-sm">
    <button class="inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative">
      <%= link_to "一覧に戻る", todos_path %>
    </button>
  </span>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <span class="inline-flex -space-x-px overflow-hidden rounded-md border bg-white shadow-sm">
    <button class="inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative">
      <%= link_to "編集", edit_todo_path(@todo) %>
    </button>
    <button class="inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative">
      <%= link_to "一覧に戻る", todos_path %>
    </button>
    <%= button_to @todo, 
      method: :delete, 
      class: "inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative",
      form_class: "inline-block" do %>
      削除
    <% end %>
  </span>
</div>